### ISSUE TITLE
Service worker error with default Web Application template

### ISSUE THREAD

**Issue by Yushell** [madskristensen/WebEssentials.AspNetCore.ServiceWorker#2] opened 2017-11-16 07:04 UTC
I created an MVC Web Application without authentication with the latest version of Visual Studio 2017 (15.4.4) and .NET Core 2.0.3. But the Service Worker fails to register. Under the Application tab in chrome tools, under Service Workers I find the following error:

```
(unknown) #1: ServiceWorker failed to install: ServiceWorker failed to handle event (event.waitUntilPromise rejected)
#1: Uncaught (in promise) TypeError: Cannot read property 'addAll' of undefined
```

The service worker code is:

```
(function () {
    'use strict';

    // Update 'version' if you need to refresh the cache
    var version = 'v1.0::CacheFirstSafe';
    var offlineUrl = "/offline.html";

    // Store core files in a cache (including a page to display when offline)
    function updateStaticCache() {
        return caches.open(version)
            .then(function (cache) {
                return cache.addAll([
                    offlineUrl,
                    
                ]);
            });
    }

    function addToCache(request, response) {
        var copy = response.clone();
        caches.open(version)
              .then(function (cache) {
                  cache.put(request, copy);
              });
    }

    self.addEventListener('install', function (event) {
        event.waitUntil(updateStaticCache());
    });

    self.addEventListener('activate', function (event) {
        event.waitUntil(
            caches.keys()
                .then(function (keys) {
                    // Remove caches whose name is no longer valid
                    return Promise.all(keys
                        .filter(function (key) {
                            return key.indexOf(version) !== 0;
                        })
                        .map(function (key) {
                            return caches.delete(key);
                        })
                    );
                })
        );
    });

    self.addEventListener('fetch', function (event) {
        var request = event.request;

        // Always fetch non-GET requests from the network
        if (request.method !== 'GET') {
            event.respondWith(
                fetch(request)
                    .catch(function () {
                        return caches.match(offlineUrl);
                    })
            );
            return;
        }

        // For HTML requests, try the network first, fall back to the cache, finally the offline page
        if (request.headers.get('Accept').indexOf('text/html') !== -1) {
            event.respondWith(
                fetch(request)
                    .then(function (response) {
                        // Stash a copy of this page in the cache
                        addToCache(request, response);
                        return response;
                    })
                    .catch(function () {
                        return caches.match(request)
                            .then(function (response) {
                                return response || caches.match(offlineUrl);
                            });
                    })
            );
            return;
        }

        // For non-HTML requests, look in the cache first, fall back to the network
        event.respondWith(
            caches.match(request)
                .then(function (response) {
                    return response || fetch(request)
                        .then(function (response) {
                            if (request.url.match(/(\?|&)v=/ig)) {
                                // Stash a copy of this file in the cache if it contains a fingerprint ala '?v=randombits'
                                addToCache(request, response);
                            }
                            return response;
                        })
                        .catch(function () {
                            // If the request is for an image, show an offline placeholder
                            if (request.headers.get('Accept').indexOf('image') !== -1) {
                                return new Response('<svg role="img" aria-labelledby="offline-title" viewBox="0 0 400 300" xmlns="http://www.w3.org/2000/svg"><title id="offline-title">Offline</title><g fill="none" fill-rule="evenodd"><path fill="#D8D8D8" d="M0 0h400v300H0z"/><text fill="#9B9B9B" font-family="Helvetica Neue,Arial,Helvetica,sans-serif" font-size="72" font-weight="bold"><tspan x="93" y="172">offline</tspan></text></g></svg>', { headers: { 'Content-Type': 'image/svg+xml' } });
                            }
                        });
                })
        );
    });

})();
```

I made no alterations to the default Startup class:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Rewrite;

namespace CorePWASample
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc();
            services.AddProgressiveWebApp();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            var options = new RewriteOptions().AddRedirectToHttps();
            app.UseRewriter(options);

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}
```

Chrome tools marks the error on the cache.**addAll()** function inside updateStaticCache()

Don't know how to solve this. The cache seems to be undefined at this moment.

**Comment by madskristensen** [comment] 2017-11-16 21:49
@Yushell, I think i figured out what the issue is. It happens when Visual Studio attaches the debugger to Chrome after you hit F5 to launch the app in the browser. Can you please try to hit Ctrl+F5 to launch Chrome without the debugger attached and see if that works?

**Comment by Yushell** [comment] 2017-11-16 21:59
It's true. It works well without the debugger. I suppose I can debug the application while on development without the service worker enabled.

I wonder if it's possible to have both working at the same time. Anyway. Thanks for your help. PWA are starting to be very important and .NET Core is just awesome. Having both together makes so much sense.

**Comment by madskristensen** [comment] 2017-11-16 21:59
I've updated the readme with instruction on how to disable script debugging or to apply this workaround https://stackoverflow.com/a/46128895

**Comment by madskristensen** [comment] 2017-11-22 19:21
The bug has been opened on the Visual Studio debugger team to get this fixed. There is nothing this project (or any other service worker implementations) can do to fix this. Closing issue

**Closed by madskristensen** 2017-11-22 19:21 UTC

**Comment by teghoz** [comment] 2018-07-19 09:42
@madskristensenI cant get mine to work I have a 404 https://localhost:44332/~/serviceworker. I think it is related to the tilde. How do I get around that

![consoleissues](https://user-images.githubusercontent.com/10187133/42934986-932af870-8b59-11e8-954b-a5823455b0a8.PNG)

**Comment by thanhxuanhd** [comment] 2018-07-26 17:19
I try with new project asp.net core 2.1 , but url serviceworker.js and manifest.json had overwrite.
Below is detail: 
![image](https://user-images.githubusercontent.com/15654411/43277356-04f35ef6-9132-11e8-816e-c7dec5ec010f.png)
![image](https://user-images.githubusercontent.com/15654411/43277384-134b3e42-9132-11e8-8977-7f1944144b01.png)

`using IdentityApplication.Data;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Rewrite;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using WebEssentials.AspNetCore.Pwa;

namespace IdentityApplication
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.Configure<CookiePolicyOptions>(options =>
            {
                // This lambda determines whether user consent for non-essential cookies is needed for a given request.
                options.CheckConsentNeeded = context => true;
                options.MinimumSameSitePolicy = SameSiteMode.None;
            });

            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(
                    Configuration.GetConnectionString("DefaultConnection")));
            services.AddDefaultIdentity<IdentityUser>()
                .AddEntityFrameworkStores<ApplicationDbContext>();

            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            services
                .AddProgressiveWebApp(new PwaOptions { RegisterServiceWorker = true, RegisterWebmanifest = true });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                app.UseHsts();
            }

            app.UseHttpsRedirection();

            var options = new RewriteOptions().AddRedirectToHttps();
            app.UseRewriter(options);

            app.UseStaticFiles();
            app.UseCookiePolicy();

            app.UseAuthentication();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}/{action=Index}/{id?}");
            });
        }
    }
}`

**Comment by rlanga** [comment] 2018-08-18 13:53
See #36 . That helped me
